// Code generated by github.com/weblfe/gorm_gen. DO NOT EDIT.
package query

import (
	"context"

	"database/sql"

	"strings"

	"gorm.io/gorm"

	"gorm.io/gorm/schema"

	"gorm.io/gorm/clause"

	gen "github.com/weblfe/gorm_gen"
	"github.com/weblfe/gorm_gen/field"

	"github.com/weblfe/gorm_gen/helper"

	"gorm.io/plugin/dbresolver"

	"github.com/weblfe/gorm_gen/tests/.gen/dal_4/model"

	"time"
)

// createMethod
func newUsers(db *gorm.DB, opts ...gen.DOOption) users {
	_users := users{}

	_users.usersDo.UseDB(db, opts...)
	_users.usersDo.UseModel(&model.Users{})

	tableName := _users.usersDo.TableName()
	_users.ALL = field.NewAsterisk(tableName)
	_users.ID = field.NewInt64(tableName, "id")
	_users.CreatedAt = field.NewTime(tableName, "created_at")
	_users.Name = field.NewString(tableName, "name")
	_users.Address = field.NewString(tableName, "address")
	_users.RegisterTime = field.NewTime(tableName, "register_time")
	_users.Alive = field.NewBool(tableName, "alive")
	_users.CompanyID = field.NewInt64(tableName, "company_id")
	_users.PrivateURL = field.NewString(tableName, "private_url")

	_users.fillFieldMap()

	return _users
}

// users struct
type users struct {
	usersDo
	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	Name         field.String // oneline
	Address      field.String
	RegisterTime field.Time
	/*
		        multiline
		line1
		line2
	*/
	Alive      field.Bool
	CompanyID  field.Int64
	PrivateURL field.String

	fieldMap map[string]field.Expr
}

// Table tableMethod
func (u users) Table(newTableName string) *users {
	u.usersDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

// As asMethod
func (u users) As(alias string) *users {
	u.usersDo.DO = *(u.usersDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

// updateMethod
func (u *users) updateTableName(table string) *users {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.Name = field.NewString(table, "name")
	u.Address = field.NewString(table, "address")
	u.RegisterTime = field.NewTime(table, "register_time")
	u.Alive = field.NewBool(table, "alive")
	u.CompanyID = field.NewInt64(table, "company_id")
	u.PrivateURL = field.NewString(table, "private_url")

	u.fillFieldMap()

	return u
}

// WithContext method
func (u *users) WithContext(ctx context.Context) IUsersDo {
	return u.usersDo.WithContext(ctx)
}

// TableName table name
func (u users) TableName() string {
	return u.usersDo.TableName()
}

// Alias method
func (u users) Alias() string {
	return u.usersDo.Alias()
}

// GetFieldByName getFieldMethod
func (u *users) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

// fillFieldMapMethod
func (u *users) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["name"] = u.Name
	u.fieldMap["address"] = u.Address
	u.fieldMap["register_time"] = u.RegisterTime
	u.fieldMap["alive"] = u.Alive
	u.fieldMap["company_id"] = u.CompanyID
	u.fieldMap["private_url"] = u.PrivateURL
}

// cloneMethod
func (u users) clone(db *gorm.DB) users {
	u.usersDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

// replaceMethod
func (u users) replaceDB(db *gorm.DB) users {
	u.usersDo.ReplaceDB(db)
	return u
}

// relationship
type usersDo struct{ gen.DO }

// IUsersDo interface
type IUsersDo interface {
	gen.SubQuery
	Debug() IUsersDo
	WithContext(ctx context.Context) IUsersDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUsersDo
	WriteDB() IUsersDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUsersDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conditions ...clause.Expression) IUsersDo
	Not(conditions ...gen.Condition) IUsersDo
	Or(conditions ...gen.Condition) IUsersDo
	Select(conditions ...field.Expr) IUsersDo
	Where(conditions ...gen.Condition) IUsersDo
	Order(conditions ...field.Expr) IUsersDo
	Distinct(cols ...field.Expr) IUsersDo
	Omit(cols ...field.Expr) IUsersDo
	Join(table schema.Tabler, on ...field.Expr) IUsersDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUsersDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUsersDo
	Group(cols ...field.Expr) IUsersDo
	Having(conditions ...gen.Condition) IUsersDo
	Limit(limit int) IUsersDo
	Offset(offset int) IUsersDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUsersDo
	Unscoped() IUsersDo
	Create(values ...*model.Users) error
	CreateInBatches(values []*model.Users, batchSize int) error
	Save(values ...*model.Users) error
	First() (*model.Users, error)
	Take() (*model.Users, error)
	Last() (*model.Users, error)
	Find() ([]*model.Users, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Users, err error)
	FindInBatches(result *[]*model.Users, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Users) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUsersDo
	Assign(attrs ...field.AssignExpr) IUsersDo
	Joins(fields ...field.RelationField) IUsersDo
	Preload(fields ...field.RelationField) IUsersDo
	FirstOrInit() (*model.Users, error)
	FirstOrCreate() (*model.Users, error)
	FindByPage(offset int, limit int) (result []*model.Users, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUsersDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FindByUsers(user model.Users) (result []model.Users)
	FindByComplexIf(user *model.Users) (result []model.Users)
	FindByIfTime(start time.Time) (result []model.Users)
	TestFor(names []string) (result model.Users, err error)
	TestForKey(names []string, name string, value string) (result model.Users, err error)
	TestForOr(names []string) (result model.Users, err error)
	TestIfInFor(names []string, name string) (result model.Users, err error)
	TestForInIf(names []string, name string) (result model.Users, err error)
	TestForInWhere(names []string, name string, forName string) (result model.Users, err error)
	TestForUserList(users []*model.Users, name string) (result model.Users, err error)
	TestForMap(param map[string]string, name string) (result model.Users, err error)
	TestIfInIf(name string) (result model.Users)
	TestMoreFor(names []string, ids []int) (result []model.Users)
	TestMoreFor2(names []string, ids []int) (result []model.Users)
	TestForInSet(users []model.Users) (err error)
	TestInsertMoreInfo(users []model.Users) (err error)
	TestIfElseFor(name string, users []model.Users) (err error)
	TestForLike(names []string) (result []model.Users)
	AddUser(name string, age int) (result sql.Result, err error)
	AddUser1(name string, age int) (rowsAffected int64, err error)
	AddUser2(name string, age int) (rowsAffected int64)
	AddUser3(name string, age int) (result sql.Result)
	AddUser4(name string, age int) (row *sql.Row)
	AddUser5(name string, age int) (rows *sql.Rows)
	AddUser6(name string, age int) (rows *sql.Rows, err error)
	FindByID(id int) (result model.Users)
	LikeSearch(name string) (result *model.Users)
	InSearch(names []string) (result []*model.Users)
	ColumnSearch(name string, names []string) (result []*model.Users)
}

// FindByUsers
//
// select * from @@table
// {{where}}
// {{if user.Name !=""}}
// name=@user.Name
// {{end}}
// {{end}}
func (u usersDo) FindByUsers(user model.Users) (result []model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if user.Name != "" {
		params = append(params, user.Name)
		whereSQL0.WriteString("name=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// FindByComplexIf
//
// select * from @@table
// {{where}}
// {{if user != nil && user.Name !=""}}
// name=@user.Name
// {{end}}
// {{end}}
func (u usersDo) FindByComplexIf(user *model.Users) (result []model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if user != nil && user.Name != "" {
		params = append(params, user.Name)
		whereSQL0.WriteString("name=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// FindByIfTime
//
// select * from @@table
// {{if !start.IsZero()}}
// created_at > start
// {{end}}
func (u usersDo) FindByIfTime(start time.Time) (result []model.Users) {
	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	if !start.IsZero() {
		generateSQL.WriteString("created_at > start ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestFor
//
// select * from @@table where
// {{for _,name:=range names}}
// name = @name and
// {{end}}
// 1=1
func (u usersDo) TestFor(names []string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	for _, name := range names {
		params = append(params, name)
		generateSQL.WriteString("name = ? and ")
	}
	generateSQL.WriteString("1=1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForKey
//
// select * from @@table where
// {{for _,name:=range names}}
// or @@name = @value
// {{end}}
// and 1=1
func (u usersDo) TestForKey(names []string, name string, value string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	for _, name := range names {
		params = append(params, value)
		generateSQL.WriteString("or " + u.Quote(name) + " = ? ")
	}
	generateSQL.WriteString("and 1=1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForOr
//
// select * from @@table
// {{where}}
// (
// {{for _,name:=range names}}
// name = @name or
// {{end}}
// {{end}}
// )
func (u usersDo) TestForOr(names []string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	whereSQL0.WriteString("( ")
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("name = ? or ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	generateSQL.WriteString(") ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestIfInFor
//
// select * from @@table where
// {{for _,name:=range names}}
// {{if name !=""}}
// name = @name or
// {{end}}
// {{end}}
// 1=2
func (u usersDo) TestIfInFor(names []string, name string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	for _, name := range names {
		if name != "" {
			params = append(params, name)
			generateSQL.WriteString("name = ? or ")
		}
	}
	generateSQL.WriteString("1=2 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForInIf
//
// select * from @@table where
// {{if name !="" }}
// {{for _,forName:=range names}}
// name = @forName or
// {{end}}
// {{end}}
// 1=2
func (u usersDo) TestForInIf(names []string, name string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users where ")
	if name != "" {
		for _, forName := range names {
			params = append(params, forName)
			generateSQL.WriteString("name = ? or ")
		}
	}
	generateSQL.WriteString("1=2 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForInWhere
//
// select * from @@table
// {{where}}
// {{for _,forName:=range names}}
// or name = @forName
// {{end}}
// {{end}}
func (u usersDo) TestForInWhere(names []string, name string, forName string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, forName := range names {
		params = append(params, forName)
		whereSQL0.WriteString("or name = ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForUserList
//
// select * from users
// {{where}}
// {{for _,user :=range users}}
// name=@user.Name
// {{end}}
// {{end}}
func (u usersDo) TestForUserList(users []*model.Users, name string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, user := range users {
		params = append(params, user.Name)
		whereSQL0.WriteString("name=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForMap
//
// select * from users
// {{where}}
// {{for key,value :=range param}}
// @@key=@value
// {{end}}
// {{end}}
func (u usersDo) TestForMap(param map[string]string, name string) (result model.Users, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for key, value := range param {
		params = append(params, value)
		whereSQL0.WriteString(u.Quote(key) + "=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestIfInIf
//
// select * from users
// {{where}}
// {{if name !="xx"}}
// {{if name !="xx"}}
// name=@name
// {{end}}
// {{end}}
// {{end}}
func (u usersDo) TestIfInIf(name string) (result model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if name != "xx" {
		if name != "xx" {
			params = append(params, name)
			whereSQL0.WriteString("name=? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestMoreFor
//
// select * from @@table
// {{where}}
// {{for _,name := range names}}
// and name=@name
// {{end}}
// {{for _,id:=range ids}}
// and id=@id
// {{end}}
// {{end}}
func (u usersDo) TestMoreFor(names []string, ids []int) (result []model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("and name=? ")
	}
	for _, id := range ids {
		params = append(params, id)
		whereSQL0.WriteString("and id=? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestMoreFor2
//
// select * from @@table
// {{where}}
// {{for _,name := range names}}
// OR (name=@name
// {{for _,id:=range ids}}
// and id=@id
// {{end}}
// and title !=@name)
// {{end}}
// {{end}}
func (u usersDo) TestMoreFor2(names []string, ids []int) (result []model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("OR (name=? ")
		for _, id := range ids {
			params = append(params, id)
			whereSQL0.WriteString("and id=? ")
		}
		params = append(params, name)
		whereSQL0.WriteString("and title !=?) ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// TestForInSet
//
// update @@table
// {{set}}
// {{for _,user:=range users}}
// name=@user.Name,
// {{end}}
// {{end}} where
func (u usersDo) TestForInSet(users []model.Users) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("update users ")
	var setSQL0 strings.Builder
	for _, user := range users {
		params = append(params, user.Name)
		setSQL0.WriteString("name=?, ")
	}
	helper.JoinSetBuilder(&generateSQL, setSQL0)
	generateSQL.WriteString("where ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestInsertMoreInfo
//
// insert into @@table(name,age)values
// {{for index ,user:=range users}}
// {{if index >0}}
// ,
// {{end}}
// (@user.Name,@user.Age)
// {{end}}
func (u usersDo) TestInsertMoreInfo(users []model.Users) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("insert into users(name,age)values ")
	for index, user := range users {
		if index > 0 {
			generateSQL.WriteString(", ")
		}
		params = append(params, user.Name)
		params = append(params, user.Age)
		generateSQL.WriteString("(?,?) ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestIfElseFor
//
// select * from @@table
// {{where}}
// {{if name =="admin"}}
// (
// {{for index,user:=range users}}
// {{if index !=0}}
// and
// {{end}}
// name like @user.Name
// {{end}}
// )
// {{else if name !="guest"}}
// {{for index,guser:=range users}}
// {{if index ==0}}
// (
// {{else}}
// and
// {{end}}
// name = @guser.Name
// {{end}}
// )
// {{else}}
// name ="guest"
// {{end}}
// {{end}}
func (u usersDo) TestIfElseFor(name string, users []model.Users) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	if name == "admin" {
		whereSQL0.WriteString("( ")
		for index, user := range users {
			if index != 0 {
				whereSQL0.WriteString("and ")
			}
			params = append(params, user.Name)
			whereSQL0.WriteString("name like ? ")
		}
		whereSQL0.WriteString(") ")
	} else if name != "guest" {
		for index, guser := range users {
			if index == 0 {
				whereSQL0.WriteString("( ")
			} else {
				whereSQL0.WriteString("and ")
			}
			params = append(params, guser.Name)
			whereSQL0.WriteString("name = ? ")
		}
		whereSQL0.WriteString(") ")
	} else {
		whereSQL0.WriteString("name =\"guest\" ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// TestForLike
//
// select * from @@table
// {{where}}
// {{for _,name:=range names}}
// name like concat("%",@name,"%") or
// {{end}}
// {{end}}
func (u usersDo) TestForLike(names []string) (result []model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("select * from users ")
	var whereSQL0 strings.Builder
	for _, name := range names {
		params = append(params, name)
		whereSQL0.WriteString("name like concat(\"%\",?,\"%\") or ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// AddUser
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser(name string, age int) (result sql.Result, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	stmt := u.UnderlyingDB().Statement
	result, err = stmt.ConnPool.ExecContext(stmt.Context, generateSQL.String(), params...) // ignore_security_alert

	return
}

// AddUser1
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser1(name string, age int) (rowsAffected int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected
	err = executeSQL.Error

	return
}

// AddUser2
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser2(name string, age int) (rowsAffected int64) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	rowsAffected = executeSQL.RowsAffected

	return
}

// AddUser3
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser3(name string, age int) (result sql.Result) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	stmt := u.UnderlyingDB().Statement
	result, _ = stmt.ConnPool.ExecContext(stmt.Context, generateSQL.String(), params...) // ignore_security_alert

	return
}

// AddUser4
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser4(name string, age int) (row *sql.Row) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	row = u.UnderlyingDB().Raw(generateSQL.String(), params...).Row() // ignore_security_alert

	return
}

// AddUser5
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser5(name string, age int) (rows *sql.Rows) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	rows, _ = u.UnderlyingDB().Raw(generateSQL.String(), params...).Rows() // ignore_security_alert

	return
}

// AddUser6
//
// INSERT INTO users (name,age) VALUES (@name,@age) ON DUPLICATE KEY UPDATE age=VALUES(age)
func (u usersDo) AddUser6(name string, age int) (rows *sql.Rows, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	params = append(params, age)
	generateSQL.WriteString("INSERT INTO users (name,age) VALUES (?,?) ON DUPLICATE KEY UPDATE age=VALUES(age) ")

	rows, err = u.UnderlyingDB().Raw(generateSQL.String(), params...).Rows() // ignore_security_alert

	return
}

// FindByID
//
// select * from users where id=@id
func (u usersDo) FindByID(id int) (result model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("select * from users where id=? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// LikeSearch
//
// SELECT * FROM @@table where name LIKE concat('%',@name,'%')
func (u usersDo) LikeSearch(name string) (result *model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM users where name LIKE concat('%',?,'%') ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// InSearch
//
// select * from @@table where name in @names
func (u usersDo) InSearch(names []string) (result []*model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, names)
	generateSQL.WriteString("select * from users where name in ? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// ColumnSearch
//
// select * from @@table where @@name in @names
func (u usersDo) ColumnSearch(name string, names []string) (result []*model.Users) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, names)
	generateSQL.WriteString("select * from users where " + u.Quote(name) + " in ? ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

func (u usersDo) Debug() IUsersDo {
	return u.withDO(u.DO.Debug())
}

func (u usersDo) WithContext(ctx context.Context) IUsersDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u usersDo) ReadDB() IUsersDo {
	return u.Clauses(dbresolver.Read)
}

func (u usersDo) WriteDB() IUsersDo {
	return u.Clauses(dbresolver.Write)
}

func (u usersDo) Session(config *gorm.Session) IUsersDo {
	return u.withDO(u.DO.Session(config))
}

func (u usersDo) Clauses(conds ...clause.Expression) IUsersDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u usersDo) Returning(value interface{}, columns ...string) IUsersDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u usersDo) Not(conds ...gen.Condition) IUsersDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u usersDo) Or(conds ...gen.Condition) IUsersDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u usersDo) Select(conds ...field.Expr) IUsersDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u usersDo) Where(conds ...gen.Condition) IUsersDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u usersDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IUsersDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u usersDo) Order(conds ...field.Expr) IUsersDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u usersDo) Distinct(cols ...field.Expr) IUsersDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u usersDo) Omit(cols ...field.Expr) IUsersDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u usersDo) Join(table schema.Tabler, on ...field.Expr) IUsersDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u usersDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUsersDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u usersDo) RightJoin(table schema.Tabler, on ...field.Expr) IUsersDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u usersDo) Group(cols ...field.Expr) IUsersDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u usersDo) Having(conds ...gen.Condition) IUsersDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u usersDo) Limit(limit int) IUsersDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u usersDo) Offset(offset int) IUsersDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u usersDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUsersDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u usersDo) Unscoped() IUsersDo {
	return u.withDO(u.DO.Unscoped())
}

func (u usersDo) Create(values ...*model.Users) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u usersDo) CreateInBatches(values []*model.Users, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u usersDo) Save(values ...*model.Users) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u usersDo) First() (*model.Users, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Users), nil
	}
}

func (u usersDo) Take() (*model.Users, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Users), nil
	}
}

func (u usersDo) Last() (*model.Users, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Users), nil
	}
}

func (u usersDo) Find() ([]*model.Users, error) {
	result, err := u.DO.Find()
	return result.([]*model.Users), err
}

func (u usersDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Users, err error) {
	buf := make([]*model.Users, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u usersDo) FindInBatches(result *[]*model.Users, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u usersDo) Attrs(attrs ...field.AssignExpr) IUsersDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u usersDo) Assign(attrs ...field.AssignExpr) IUsersDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u usersDo) Joins(fields ...field.RelationField) IUsersDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u usersDo) Preload(fields ...field.RelationField) IUsersDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u usersDo) FirstOrInit() (*model.Users, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Users), nil
	}
}

func (u usersDo) FirstOrCreate() (*model.Users, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Users), nil
	}
}

func (u usersDo) FindByPage(offset int, limit int) (result []*model.Users, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u usersDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u usersDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u usersDo) Delete(models ...*model.Users) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *usersDo) withDO(do gen.Dao) *usersDo {
	u.DO = *do.(*gen.DO)
	return u
}
